<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin 0.9.4
// Source: dota_commonmessages.proto
//   Date: 2012-04-27 16:14:32

namespace  {

  class CDOTAMsg_LocationPing extends \DrSlump\Protobuf\Message {

    /**  @var int */
    public $x = null;
    
    /**  @var int */
    public $y = null;
    
    /**  @var int */
    public $target = null;
    
    /**  @var boolean */
    public $direct_ping = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, '.CDOTAMsg_LocationPing');

      // OPTIONAL INT32 x = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "x";
      $f->type      = \DrSlump\Protobuf::TYPE_INT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL INT32 y = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "y";
      $f->type      = \DrSlump\Protobuf::TYPE_INT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL INT32 target = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "target";
      $f->type      = \DrSlump\Protobuf::TYPE_INT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL BOOL direct_ping = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "direct_ping";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <x> has a value
     *
     * @return boolean
     */
    public function hasX(){
      return $this->_has(1);
    }
    
    /**
     * Clear <x> value
     *
     * @return \CDOTAMsg_LocationPing
     */
    public function clearX(){
      return $this->_clear(1);
    }
    
    /**
     * Get <x> value
     *
     * @return int
     */
    public function getX(){
      return $this->_get(1);
    }
    
    /**
     * Set <x> value
     *
     * @param int $value
     * @return \CDOTAMsg_LocationPing
     */
    public function setX( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <y> has a value
     *
     * @return boolean
     */
    public function hasY(){
      return $this->_has(2);
    }
    
    /**
     * Clear <y> value
     *
     * @return \CDOTAMsg_LocationPing
     */
    public function clearY(){
      return $this->_clear(2);
    }
    
    /**
     * Get <y> value
     *
     * @return int
     */
    public function getY(){
      return $this->_get(2);
    }
    
    /**
     * Set <y> value
     *
     * @param int $value
     * @return \CDOTAMsg_LocationPing
     */
    public function setY( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <target> has a value
     *
     * @return boolean
     */
    public function hasTarget(){
      return $this->_has(3);
    }
    
    /**
     * Clear <target> value
     *
     * @return \CDOTAMsg_LocationPing
     */
    public function clearTarget(){
      return $this->_clear(3);
    }
    
    /**
     * Get <target> value
     *
     * @return int
     */
    public function getTarget(){
      return $this->_get(3);
    }
    
    /**
     * Set <target> value
     *
     * @param int $value
     * @return \CDOTAMsg_LocationPing
     */
    public function setTarget( $value){
      return $this->_set(3, $value);
    }
    
    /**
     * Check if <direct_ping> has a value
     *
     * @return boolean
     */
    public function hasDirectPing(){
      return $this->_has(4);
    }
    
    /**
     * Clear <direct_ping> value
     *
     * @return \CDOTAMsg_LocationPing
     */
    public function clearDirectPing(){
      return $this->_clear(4);
    }
    
    /**
     * Get <direct_ping> value
     *
     * @return boolean
     */
    public function getDirectPing(){
      return $this->_get(4);
    }
    
    /**
     * Set <direct_ping> value
     *
     * @param boolean $value
     * @return \CDOTAMsg_LocationPing
     */
    public function setDirectPing( $value){
      return $this->_set(4, $value);
    }
  }
}

namespace  {

  class CDOTAMsg_MapLine extends \DrSlump\Protobuf\Message {

    /**  @var int */
    public $x = null;
    
    /**  @var int */
    public $y = null;
    
    /**  @var boolean */
    public $initial = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, '.CDOTAMsg_MapLine');

      // OPTIONAL INT32 x = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "x";
      $f->type      = \DrSlump\Protobuf::TYPE_INT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL INT32 y = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "y";
      $f->type      = \DrSlump\Protobuf::TYPE_INT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL BOOL initial = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "initial";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <x> has a value
     *
     * @return boolean
     */
    public function hasX(){
      return $this->_has(1);
    }
    
    /**
     * Clear <x> value
     *
     * @return \CDOTAMsg_MapLine
     */
    public function clearX(){
      return $this->_clear(1);
    }
    
    /**
     * Get <x> value
     *
     * @return int
     */
    public function getX(){
      return $this->_get(1);
    }
    
    /**
     * Set <x> value
     *
     * @param int $value
     * @return \CDOTAMsg_MapLine
     */
    public function setX( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <y> has a value
     *
     * @return boolean
     */
    public function hasY(){
      return $this->_has(2);
    }
    
    /**
     * Clear <y> value
     *
     * @return \CDOTAMsg_MapLine
     */
    public function clearY(){
      return $this->_clear(2);
    }
    
    /**
     * Get <y> value
     *
     * @return int
     */
    public function getY(){
      return $this->_get(2);
    }
    
    /**
     * Set <y> value
     *
     * @param int $value
     * @return \CDOTAMsg_MapLine
     */
    public function setY( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <initial> has a value
     *
     * @return boolean
     */
    public function hasInitial(){
      return $this->_has(3);
    }
    
    /**
     * Clear <initial> value
     *
     * @return \CDOTAMsg_MapLine
     */
    public function clearInitial(){
      return $this->_clear(3);
    }
    
    /**
     * Get <initial> value
     *
     * @return boolean
     */
    public function getInitial(){
      return $this->_get(3);
    }
    
    /**
     * Set <initial> value
     *
     * @param boolean $value
     * @return \CDOTAMsg_MapLine
     */
    public function setInitial( $value){
      return $this->_set(3, $value);
    }
  }
}

